name: GitHub Pages deploy
on:
  push:
    branches:
      - master
jobs:
  checkout-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install
      run: yarn --no-progress --non-interactive --no-lockfile
    - name: Build
      run: yarn build
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@master
      env:
        EMAIL: mohammedsharaf@live.de
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: build
