name: buildDeploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn --no-progress --non-interactive --no-lockfile
      - name: Build
        run: yarn build
      - name: Configure Git
        run: |
          git config user.email "mohammedsharaf@live.de";
          git config user.name "Sharaf0";
      - name: Deploy
        run: yarn deploy
